services:
  - type: web
    name: mmv
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: MMV
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: btg55vpzbpf24qdui2y1-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: btg55vpzbpf24qdui2y1
      - key: DB_USERNAME
        value: ua3vcj0hrnyoylwv
      - key: DB_PASSWORD
        value: 5ZL5zvJW3mOwEKNils3G
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
