services:
  - type: web
    name: mmv
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: MMV
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mmv-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mmv-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mmv-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mmv-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mmv-db
          property: password

databases:
  - name: mmv-db
    plan: free
    databaseName: mmv_db
    user: mmv_user
